name: Green Shop Auto Build
on:
  push:
    branches: [ main ]

env:
  # भविष्य के अपडेट के लिए Node 24 को इनेबल करना
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 🚀

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24 # यहाँ हमने 18 की जगह 24 कर दिया है ✨

      - name: Install NPM
        run: npm install

      - name: Create Build
        run: npm run build

      - name: Zip The Build Folder
        run: |
          mkdir -p public/build
          zip -r titan-build.zip public/build

      - name: Save My Build
        uses: actions/upload-artifact@v4
        with:
          name: GreenShop-Build
          path: titan-build.zip
